export const MIN_LEDGER_STORAGE_GB = 0;
export const MAX_LEDGER_STORAGE_GB = 100;
export const DEFAULT_LEDGER_STORAGE_GB = 20;
export const CLUSTER_UPDATE_TIMEOUT = 10000;
export const DEFAULT_MINIMUM_DEPOSIT_LAMPORTS = 10000;
